name = "up-for-a-ride-worker"
main = "apps/worker/worker.ts"
compatibility_date = "2024-05-01"

# D1 binding
[[d1_databases]]
binding = "DB"
database_name = "up_for_a_ride_db"
database_id = "7a37a2c9-5548-483c-9527-845dc79d08c4"

[vars]
OCR_SPACE_API_KEY = "YK82567465988957"

# Optional: dev settings
[dev]
port = 8787
local_protocol = "http"
